"""Initial migration

Revision ID: d1512530215b
Revises: 
Create Date: 2025-05-26 16:17:10.739576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1512530215b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('subregion', sa.String(), nullable=True),
    sa.Column('independent', sa.Boolean(), nullable=True),
    sa.Column('google_maps_url', sa.String(), nullable=True),
    sa.Column('open_street_map_url', sa.String(), nullable=True),
    sa.Column('capital_name', sa.String(), nullable=True),
    sa.Column('capital_latitude', sa.Float(), nullable=True),
    sa.Column('capital_longitude', sa.Float(), nullable=True),
    sa.Column('flag_png_url', sa.String(), nullable=True),
    sa.Column('flag_svg_url', sa.String(), nullable=True),
    sa.Column('flag_alt', sa.String(), nullable=True),
    sa.Column('coat_of_arms_png_url', sa.String(), nullable=True),
    sa.Column('coat_of_arms_svg_url', sa.String(), nullable=True),
    sa.Column('borders', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_table('names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('count_of_requests', sa.Integer(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_names_id'), 'names', ['id'], unique=False)
    op.create_index(op.f('ix_names_name'), 'names', ['name'], unique=True)
    op.create_table('name_country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['name_id'], ['names.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_name_country_id'), 'name_country', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_name_country_id'), table_name='name_country')
    op.drop_table('name_country')
    op.drop_index(op.f('ix_names_name'), table_name='names')
    op.drop_index(op.f('ix_names_id'), table_name='names')
    op.drop_table('names')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
